### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mrdudz** [f4grx/hc11-sim#1]
could you add a license please? (looking for a 68hc11 core i can use in a project)

**Comment by f4grx** [comment]
Hi,
Would you accept the mozilla public license?

This licence specifies that the source files must remain open source and you have to contribute your fixes, but the rest of the project does not have to be.

I have only tested the instructions that happened to be required in my firmware, I make no garantee, you would have to fix it to make it work, right?

If you're ok I'll update the files to indicate the mpl.

Thanks!

**Comment by f4grx** [comment]
Well, this license seems to work, so this is done here (c618c7982542499cf05e68eaabeb6824e068663b)

If you have any problem with this, please tell me without hesitation, I can update it.

The goal is to help you, not to bother you.

**Comment by f4grx** [comment]
Also you can tell me what you want to do with it, I am very interested by 8-bit stuff and maybe I can help develop what you miss.

**Comment by f4grx** [comment]
Okay, so the MPL2 I added might help you. I am OK with you using this in a commercial project, BUT please do extensive testing and corrections to get everything working fine, because I did this as a hobby project, it was sufficient for me, but it is not tested enough. Please torture it with numerous test cases! Have a look at test.sh in the repository for examples of tests.
I can give you light support to understand the code so you can improve it, if you end up needing extensive support, I can also do it, but as a contract job.
We can continue discussing by email if you prefer.

**Comment by mrdudz** [comment]
As said, just doing some research now - will come back if this will actually become reality :)

**Comment by slorquet** [comment]
Hi, FYI GDB has been fixed in trunk now. m68hc11-elf-run works as expected now, the INIT register is working. This will be available in the next binutils-gdb release (13).

**Comment by f4grx** [comment]
Hello, any update on the subject?
